export type ConnectMessageRecord = {
  acknowledgedAt?: string;
  allowsCallbackRequest?: boolean;
  appointmentId?: string;
  appointmentStartsAt?: string;
  appointmentTitle?: string;
  audioArtifactId?: string;
  audioDurationMs?: number;
  audioMimeType?: string;
  audioUrl?: string;
  body: string;
  callbackRequestedAt?: string;
  clientMessageId?: string;
  createdAt: string;
  deliveredAt?: string;
  from: string;
  heardAt?: string;
  id: string;
  mainConnectUserPersonId?: string;
  metadata?: Record<string, unknown>;
  messageType?: string;
  receiverDeviceId?: string;
  readAt?: string;
  receiverId?: string;
  requiresAcknowledgement?: boolean;
  senderRole?: string;
  senderUserId?: string;
  source?: string;
  to: string;
  transcript?: string;
  transcriptStatus?: string;
  updatedAt?: string;
};
