"use client";

import { formatAdminDate, shortId } from "./adminFormatters";
import type { AdminWorkspaceProps } from "./AdminWorkspace";

// Admin state still originates in CarePlandPers during the route split.
// This adapter keeps the panel wiring owned by the Admin island while that state moves over gradually.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AdminWorkspaceSourceProps = Record<string, any>;

export function createAdminWorkspaceProps({
  activeAdminTopTab,
  adminAccessEvents,
  adminAttentionFor,
  adminDashboardFollowupCount,
  adminDashboardNewCount,
  adminEmailUpdateCurrentEmail,
  adminEmailUpdateNewEmail,
  adminEmailUpdateReason,
  adminEmailUpdateResult,
  adminIntegrationErrorRowKey,
  adminIntegrationErrorStats,
  adminIntegrationErrors,
  adminLastViewedAt,
  adminReadonlyPanelRef,
  adminReadonlySnapshot,
  adminRevealedSensitiveData,
  adminSampleEmail,
  adminSampleForceDeclined,
  adminSampleStatus,
  adminSupportTickets,
  adminTab,
  adminTabForTopTab,
  adminTicketCategory,
  adminTicketChangeNote,
  adminTicketInternalNote,
  adminTicketNeedsFollowup,
  adminTicketPriority,
  adminTicketReplyBody,
  adminTicketStatus,
  adminUserActivity,
  adminUserActivityFilter,
  adminUserActivitySort,
  adminUserActivityStats,
  agentEscalationGuidance,
  agentKnowledgeAutomationSettings,
  agentKnowledgeChangeNote,
  agentKnowledgeCheckRuns,
  agentKnowledgeProposalDrafts,
  agentKnowledgeProposalNotes,
  agentKnowledgeProposalPublishNote,
  agentKnowledgeProposals,
  agentKnowledgeVersions,
  agentKnownLimitations,
  agentProductFacts,
  agentVoiceGuidance,
  aiAdminTab,
  aiInstructionVersion,
  aiInstructionVersions,
  aiOperationCostError,
  aiOperationCostRangeDays,
  aiOperationCostSummary,
  aiOperationCostUserSummary,
  aiOperationCostViewMode,
  aiWorkflows,
  allAdminIntegrationErrorsSelected,
  analyzingAssistantReviews,
  appContentBody,
  appContentCategories,
  appContentChangeNote,
  appContentDescription,
  appContentLabel,
  appContentOptions,
  appContentSaveMessage,
  appContentVersions,
  appSessionSettings,
  appointments,
  askModuleLabInput,
  askModuleLabKey,
  askModuleLabResults,
  askRecommendationDecisionSummary,
  askRecommendationDecisions,
  askReviewNote,
  askReviewRoutingState,
  askReviewSubmissions,
  askRoutingSettingsDraft,
  askSubmissionLinks,
  assistantAnalysisResult,
  assistantAnalysisRunNote,
  assistantAnalysisRunStatus,
  assistantAnalysisRuns,
  assistantInteractionUserLabel,
  assistantReviewAdminReviews,
  assistantReviewConfidenceFilter,
  assistantReviewHasFeedbackOnly,
  assistantReviewInteractions,
  assistantReviewNote,
  assistantReviewOutcomeFilter,
  assistantReviewPromptFilter,
  assistantReviewPromptVersions,
  assistantReviewRecommendedAction,
  assistantReviewStatus,
  cancelEditingProductMgmtItem,
  carePrepHistory,
  closeAdminReadonlyUserView,
  createProductItemFromAskRecommendation,
  createSupportTicketFromAskRecommendation,
  deleteSelectedAdminIntegrationErrors,
  deletingAdminIntegrationErrors,
  draftSourceVersion,
  earlyAccessIntakeAdminNotes,
  earlyAccessIntakeDraft,
  earlyAccessIntakeFilter,
  earlyAccessIntakeRows,
  earlyAccessIntakeStats,
  editingProductMgmtItemId,
  expandedAdminUserCareVipRows,
  filteredAdminUserActivity,
  filteredAppContentOptions,
  filteredAssistantReviewInteractions,
  filteredEarlyAccessIntakeRows,
  formatDate,
  formatDateOnly,
  handleAddAdminInternalNote,
  handleAddAdminTicketReply,
  handleAdminUpdateUserEmail,
  handleAnalyzeFilteredAssistantReviews,
  handleChangeAdminTab,
  handleChangeAiOperationCostRange,
  handleChangeAiAdminTab,
  handleChangeAiWorkflow,
  handleChangeAppContentCategory,
  handleChangeAppContentKey,
  handleChangeHistoryAppointment,
  handleChangeProductMgmtSection,
  handleCreateAssistantAdminReview,
  handleCreateEarlyAccessIntake,
  handleCreateProductMgmtArea,
  handleCreateProductMgmtItem,
  handleLoadAdminSampleStatus,
  handlePublishAgentKnowledgeProposal,
  handleQueueAgentKnowledgeManualCheck,
  handleResolveProductMgmtItem,
  handleRetireProductMgmtArea,
  handleRevertAppContent,
  handleRevertInstructionVersion,
  handleReviewAgentKnowledgeProposalItem,
  handleRunAskModuleLab,
  handleSaveAgentKnowledge,
  handleSaveAgentKnowledgeAutomationSettings,
  handleSaveAiInstructions,
  handleSaveAppContent,
  handleSaveAppSessionSettings,
  handleSeedAdminSampleData,
  handleUpdateAdminTicketStatus,
  handleUpdateAskReview,
  handleUpdateAskRoutingSettings,
  handleUpdateAssistantAnalysisRun,
  handleUpdateEarlyAccessIntake,
  handleUpdateProductMgmtItem,
  historyAppointmentId,
  instructionChangeNote,
  instructionModel,
  instructionOutputSchema,
  instructionSystemPrompt,
  instructionUserPrompt,
  intakeHistory,
  isNewForAdmin,
  loadAdminAccessEvents,
  loadAdminAttentionOverview,
  loadAdminIntegrationErrors,
  loadAdminSupportTickets,
  loadAdminUserActivity,
  loadAgentKnowledgeProposals,
  loadAiInstructions,
  loadAppContent,
  loadAskReviewSubmissions,
  loadAssistantReviewInteractions,
  loadCarePrepHistory,
  loadEarlyAccessIntake,
  loadInstructionVersionIntoEditor,
  loadIntakeHistory,
  loadingAdminAccessEvents,
  loadingAdminIntegrationErrors,
  loadingAdminReadonlyUserId,
  loadingAdminSampleStatus,
  loadingAdminTickets,
  loadingAdminUserActivity,
  loadingAgentKnowledgeProposals,
  loadingAiOperationCosts,
  loadingAppContent,
  loadingAskReviews,
  loadingAskRoutingSettings,
  loadingAssistantReviews,
  loadingCarePrepHistory,
  loadingEarlyAccessIntake,
  loadingInstructions,
  loadingProductMgmt,
  newProductMgmtAreaDescription,
  newProductMgmtAreaLabel,
  newProductMgmtBody,
  newProductMgmtChangeNote,
  newProductMgmtPriority,
  newProductMgmtStatus,
  newProductMgmtTitle,
  openAdminReadonlyUserView,
  openAskRelatedItem,
  openAskSubmissionReview,
  productMgmtAreas,
  productMgmtItemDraft,
  productMgmtItems,
  publishingAgentKnowledgeProposalId,
  queueingAgentKnowledgeRun,
  recordAskRecommendationDecision,
  resetAppContentEditor,
  resolveAskAnswerRecommendation,
  resolvingProductMgmtItemId,
  retiringProductMgmtAreaId,
  revealAdminSensitiveData,
  revealingAdminSensitiveKey,
  revertingAppContentForId,
  revertingInstructionForId,
  runningAskModuleLab,
  sampleDataStatusText,
  saveAdminContactDetails,
  savingAdminContactDetails,
  savingAdminTicketReply,
  savingAdminTicketStatus,
  savingAgentKnowledge,
  savingAgentKnowledgeAutomationSettings,
  savingAgentKnowledgeProposalItemId,
  savingAppContent,
  savingAppSessionSettings,
  savingAskReview,
  savingAskReviewAction,
  savingAskRoutingSettings,
  savingAssistantAdminReview,
  savingAssistantAnalysisRunReview,
  savingEarlyAccessIntake,
  savingInstructions,
  savingProductMgmtArea,
  savingProductMgmtEditItemId,
  savingProductMgmtItem,
  seedingAdminSampleData,
  selectAdminTicket,
  selectAskReviewSubmission,
  selectAssistantAnalysisRun,
  selectedAdminIntegrationErrorKeys,
  selectedAdminTicket,
  selectedAdminTicketMessages,
  selectedAgentKnowledgeProposal,
  selectedAgentKnowledgeProposalItems,
  selectedAgentKnowledgeProposalPublishableCount,
  selectedAiWorkflow,
  selectedAiWorkflowConfig,
  selectedAppContent,
  selectedAppContentCategory,
  selectedAppContentCategoryConfig,
  selectedAppContentKey,
  selectedAskReviewSubmission,
  selectedAssistantAdminReviews,
  selectedAssistantAnalysisRun,
  selectedAssistantReviewInteraction,
  selectedProductMgmtArea,
  selectedProductMgmtItems,
  selectedProductMgmtSection,
  selectedProductMgmtSectionConfig,
  selectedVisibleAdminIntegrationErrorKeys,
  setAdminEmailUpdateCurrentEmail,
  setAdminEmailUpdateNewEmail,
  setAdminEmailUpdateReason,
  setAdminEmailUpdateResult,
  setAdminSampleEmail,
  setAdminSampleForceDeclined,
  setAdminSampleStatus,
  setAdminTicketCategory,
  setAdminTicketChangeNote,
  setAdminTicketInternalNote,
  setAdminTicketNeedsFollowup,
  setAdminTicketPriority,
  setAdminTicketReplyBody,
  setAdminTicketStatus,
  setAdminUserActivityFilter,
  setAgentEscalationGuidance,
  setAiOperationCostViewMode,
  setAgentKnowledgeAutomationSettings,
  setAgentKnowledgeChangeNote,
  setAgentKnowledgeProposalDrafts,
  setAgentKnowledgeProposalNotes,
  setAgentKnowledgeProposalPublishNote,
  setAgentKnownLimitations,
  setAgentProductFacts,
  setAgentVoiceGuidance,
  setAppContentBody,
  setAppContentChangeNote,
  setAppContentDescription,
  setAppContentLabel,
  setAppSessionSettings,
  setAskModuleLabInput,
  setAskModuleLabKey,
  setAskReviewNote,
  setAskReviewRoutingState,
  setAskRoutingSettingsDraft,
  setAssistantAnalysisRunNote,
  setAssistantAnalysisRunStatus,
  setAssistantReviewConfidenceFilter,
  setAssistantReviewHasFeedbackOnly,
  setAssistantReviewNote,
  setAssistantReviewOutcomeFilter,
  setAssistantReviewPromptFilter,
  setAssistantReviewRecommendedAction,
  setAssistantReviewStatus,
  setEarlyAccessIntakeAdminNotes,
  setEarlyAccessIntakeFilter,
  setExpandedAdminUserCareVipRows,
  setInstructionChangeNote,
  setInstructionModel,
  setInstructionOutputSchema,
  setInstructionSystemPrompt,
  setInstructionUserPrompt,
  setNewProductMgmtAreaDescription,
  setNewProductMgmtAreaLabel,
  setNewProductMgmtBody,
  setNewProductMgmtChangeNote,
  setNewProductMgmtPriority,
  setNewProductMgmtStatus,
  setNewProductMgmtTitle,
  setSelectedAgentKnowledgeProposalId,
  setSelectedAiWorkflow,
  setSelectedAssistantReviewId,
  setShowProductMgmtAreaForm,
  showProductMgmtAreaForm,
  startEditingProductMgmtItem,
  stickySecondaryOffset,
  supportAdminNavItems,
  supportAdminTabs,
  supportAnalysisStatusLabel,
  systemAdminNavItems,
  systemAdminTabs,
  toggleAdminIntegrationErrorSelection,
  toggleAdminUserActivitySort,
  toggleAllAdminIntegrationErrors,
  topAdminNavItems,
  updateEarlyAccessIntakeDraft,
  updateProductMgmtItemDraft,
  updatingAdminUserEmail,
  updatingEarlyAccessIntakeId,
  usersAdminNavItems,
  visibleProductMgmtSections,
}: AdminWorkspaceSourceProps): AdminWorkspaceProps {
  return {
    activeSecondaryKey: adminTab,
    activeTopKey: activeAdminTopTab,
    ai: {
                  adminAttentionFor,
                  agentEscalationGuidance,
                  agentKnowledgeAutomationSettings,
                  agentKnowledgeChangeNote,
                  agentKnowledgeCheckRuns,
                  agentKnowledgeProposalDrafts,
                  agentKnowledgeProposalNotes,
                  agentKnowledgeProposalPublishNote,
                  agentKnowledgeProposals,
                  agentKnowledgeVersions,
                  agentKnownLimitations,
                  agentProductFacts,
                  agentVoiceGuidance,
                  aiAdminTab,
                  aiInstructionVersion,
                  aiInstructionVersions,
                  aiWorkflows,
                  appointments,
                  carePrepHistory,
                  draftSourceVersion,
                  formatDate,
                  handleChangeAiAdminTab,
                  handleChangeAiWorkflow: (workflowKey: string) =>
                    handleChangeAiWorkflow(workflowKey),
                  handlePublishAgentKnowledgeProposal,
                  handleQueueAgentKnowledgeManualCheck,
                  handleReviewAgentKnowledgeProposalItem,
                  handleRevertInstructionVersion,
                  handleSaveAgentKnowledge,
                  handleSaveAgentKnowledgeAutomationSettings,
                  handleSaveAiInstructions,
                  historyAppointmentId,
                  instructionChangeNote,
                  instructionModel,
                  instructionOutputSchema,
                  instructionSystemPrompt,
                  instructionUserPrompt,
                  intakeHistory,
                  loadAgentKnowledgeProposals,
                  loadAiInstructions,
                  loadCarePrepHistory,
                  loadInstructionVersionIntoEditor,
                  loadIntakeHistory,
                  loadingAgentKnowledgeProposals,
                  loadingCarePrepHistory,
                  loadingInstructions,
                  onChangeAgentKnowledgeAutomationSettings: (
                    patch: Record<string, unknown>
                  ) =>
                    setAgentKnowledgeAutomationSettings(
                      (current: Record<string, unknown>) => ({
                        ...current,
                        ...patch,
                      })
                    ),
                  onChangeAgentKnowledgeProposalDraft: (
                    itemId: string,
                    value: string
                  ) =>
                    setAgentKnowledgeProposalDrafts(
                      (current: Record<string, string>) => ({
                        ...current,
                        [itemId]: value,
                      })
                    ),
                  onChangeAgentKnowledgeProposalNote: (
                    itemId: string,
                    value: string
                  ) =>
                    setAgentKnowledgeProposalNotes(
                      (current: Record<string, string>) => ({
                        ...current,
                        [itemId]: value,
                      })
                    ),
                  onChangeHistoryAppointment: handleChangeHistoryAppointment,
                  onLoadAgentKnowledgeContent: () =>
                    loadAppContent("support_agent_product_facts"),
                  publishingAgentKnowledgeProposalId,
                  queueingAgentKnowledgeRun,
                  revertingInstructionForId,
                  savingAgentKnowledge,
                  savingAgentKnowledgeAutomationSettings,
                  savingAgentKnowledgeProposalItemId,
                  savingInstructions,
                  selectedAgentKnowledgeProposal,
                  selectedAgentKnowledgeProposalItems,
                  selectedAgentKnowledgeProposalPublishableCount,
                  selectedAiWorkflow,
                  selectedAiWorkflowConfig,
                  setAgentEscalationGuidance,
                  setAgentKnowledgeChangeNote,
                  setAgentKnowledgeProposalPublishNote,
                  setAgentKnownLimitations,
                  setAgentProductFacts,
                  setAgentVoiceGuidance,
                  setInstructionChangeNote,
                  setInstructionModel,
                  setInstructionOutputSchema,
                  setInstructionSystemPrompt,
                  setInstructionUserPrompt,
                  setSelectedAgentKnowledgeProposalId,
                },
    assistantReview: {
                  ask: {
                    decisions: askRecommendationDecisions,
                    decisionSummaryRows: askRecommendationDecisionSummary,
                    formatDate,
                    links: askSubmissionLinks,
                    loading: loadingAskReviews,
                    loadingSettings: loadingAskRoutingSettings,
                    moduleLabInput: askModuleLabInput,
                    moduleLabKey: askModuleLabKey,
                    moduleLabResults: askModuleLabResults,
                    moduleLabRunning: runningAskModuleLab,
                    onCreateProductItem: createProductItemFromAskRecommendation,
                    onCreateSupportTicket: createSupportTicketFromAskRecommendation,
                    onOpenRelatedItem: openAskRelatedItem,
                    onRecordDecision: recordAskRecommendationDecision,
                    onRefresh: loadAskReviewSubmissions,
                    onResolveAnswer: resolveAskAnswerRecommendation,
                    onRunModuleLab: handleRunAskModuleLab,
                    onSelectSubmission: selectAskReviewSubmission,
                    onSetModuleLabInput: setAskModuleLabInput,
                    onSetModuleLabKey: setAskModuleLabKey,
                    onSetReviewNote: setAskReviewNote,
                    onSetRoutingState: setAskReviewRoutingState,
                    onSetSettingsDraft: setAskRoutingSettingsDraft,
                    onUpdateReview: handleUpdateAskReview,
                    onUpdateSettings: handleUpdateAskRoutingSettings,
                    reviewNote: askReviewNote,
                    routingState: askReviewRoutingState,
                    savingAction: savingAskReviewAction,
                    savingReview: savingAskReview,
                    savingSettings: savingAskRoutingSettings,
                    selectedSubmission: selectedAskReviewSubmission,
                    settingsDraft: askRoutingSettingsDraft,
                    submissions: askReviewSubmissions,
                  },
                  support: {
                    adminLastViewedAt,
                    analyzingAssistantReviews,
                    assistantAnalysisResult,
                    assistantAnalysisRunNote,
                    assistantAnalysisRuns,
                    assistantAnalysisRunStatus,
                    assistantInteractionUserLabel,
                    assistantReviewAdminReviews,
                    assistantReviewConfidenceFilter,
                    assistantReviewHasFeedbackOnly,
                    assistantReviewInteractions,
                    assistantReviewNote,
                    assistantReviewOutcomeFilter,
                    assistantReviewPromptFilter,
                    assistantReviewPromptVersions,
                    assistantReviewRecommendedAction,
                    assistantReviewStatus,
                    filteredAssistantReviewInteractions,
                    formatDate,
                    handleAnalyzeFilteredAssistantReviews,
                    handleCreateAssistantAdminReview,
                    handleUpdateAssistantAnalysisRun,
                    isNewForAdmin,
                    loadAssistantReviewInteractions,
                    loadingAssistantReviews,
                    savingAssistantAdminReview,
                    savingAssistantAnalysisRunReview,
                    selectAssistantAnalysisRun,
                    selectedAssistantAdminReviews,
                    selectedAssistantAnalysisRun,
                    selectedAssistantReviewInteraction,
                    setAssistantAnalysisRunNote,
                    setAssistantAnalysisRunStatus,
                    setAssistantReviewConfidenceFilter,
                    setAssistantReviewHasFeedbackOnly,
                    setAssistantReviewNote,
                    setAssistantReviewOutcomeFilter,
                    setAssistantReviewPromptFilter,
                    setAssistantReviewRecommendedAction,
                    setAssistantReviewStatus,
                    setSelectedAssistantReviewId,
                    supportAnalysisStatusLabel,
                  },
                },
    audit: {
                  activeKey: adminTab,
                  formatAdminDate,
                  loading: loadingAdminAccessEvents,
                  navItems: usersAdminNavItems,
                  onRefresh: loadAdminAccessEvents,
                  onSelectTab: handleChangeAdminTab,
                  rows: adminAccessEvents,
                  shortId,
                  userRows: adminUserActivity,
                },
    content: {
                  appContentBody,
                  appContentCategories,
                  appContentChangeNote,
                  appContentDescription,
                  appContentLabel,
                  appContentOptions,
                  appContentSaveMessage,
                  appContentVersions,
                  filteredAppContentOptions,
                  formatDate,
                  handleChangeAppContentCategory,
                  handleChangeAppContentKey,
                  handleRevertAppContent,
                  handleSaveAppContent,
                  loadAppContent,
                  loadingAppContent,
                  resetAppContentEditor,
                  revertingAppContentForId,
                  savingAppContent,
                  selectedAppContent,
                  selectedAppContentCategory,
                  selectedAppContentCategoryConfig,
                  selectedAppContentKey,
                  setAppContentBody,
                  setAppContentChangeNote,
                  setAppContentDescription,
                  setAppContentLabel,
                },
    dashboard: {
                  aiOperationCostError,
                  aiOperationCostRangeDays,
                  aiOperationCostRows: aiOperationCostSummary,
                  aiOperationCostUserRows: aiOperationCostUserSummary,
                  aiOperationCostViewMode,
                  followupCount: adminDashboardFollowupCount,
                  loadingAiOperationCosts,
                  newCount: adminDashboardNewCount,
                  onChangeAiOperationCostRange: handleChangeAiOperationCostRange,
                  onChangeAiOperationCostViewMode: setAiOperationCostViewMode,
                  onOpenPrioritizationPrompt: () => {
                    setSelectedAiWorkflow("admin_hq_prioritization");
                    void handleChangeAdminTab("ai");
                  },
                  onRefreshSignals: loadAdminAttentionOverview,
                },
    errors: {
                  allSelected: allAdminIntegrationErrorsSelected,
                  deleting: deletingAdminIntegrationErrors,
                  formatAdminDate,
                  lastViewedAt: adminLastViewedAt("admin_tab", "errors"),
                  loading: loadingAdminIntegrationErrors,
                  onDeleteSelected: deleteSelectedAdminIntegrationErrors,
                  onRefresh: loadAdminIntegrationErrors,
                  onToggleAll: toggleAllAdminIntegrationErrors,
                  onToggleRow: toggleAdminIntegrationErrorSelection,
                  rowKey: adminIntegrationErrorRowKey,
                  rows: adminIntegrationErrors,
                  selectedKeys: selectedAdminIntegrationErrorKeys,
                  selectedVisibleCount:
                    selectedVisibleAdminIntegrationErrorKeys.length,
                  stats: adminIntegrationErrorStats,
                },
    intake: {
                  activeKey: adminTab,
                  adminNotes: earlyAccessIntakeAdminNotes,
                  draft: earlyAccessIntakeDraft,
                  filter: earlyAccessIntakeFilter,
                  filteredRows: filteredEarlyAccessIntakeRows,
                  formatAdminDate,
                  loading: loadingEarlyAccessIntake,
                  navItems: usersAdminNavItems,
                  onCreate: handleCreateEarlyAccessIntake,
                  onRefresh: loadEarlyAccessIntake,
                  onSelectTab: handleChangeAdminTab,
                  onUpdateDraft: updateEarlyAccessIntakeDraft,
                  onUpdateRow: handleUpdateEarlyAccessIntake,
                  rows: earlyAccessIntakeRows,
                  saving: savingEarlyAccessIntake,
                  setAdminNotes: setEarlyAccessIntakeAdminNotes,
                  setFilter: setEarlyAccessIntakeFilter,
                  stats: earlyAccessIntakeStats,
                  updatingId: updatingEarlyAccessIntakeId,
                },
    onSelectSecondary: handleChangeAdminTab,
    onSelectTop: (topTab: string) =>
                  handleChangeAdminTab(adminTabForTopTab(topTab)),
    product: {
                  cancelEditingProductMgmtItem,
                  editingProductMgmtItemId,
                  formatDate,
                  handleChangeProductMgmtSection,
                  handleCreateProductMgmtArea,
                  handleCreateProductMgmtItem,
                  handleResolveProductMgmtItem,
                  handleRetireProductMgmtArea,
                  handleUpdateProductMgmtItem,
                  loadingProductMgmt,
                  newProductMgmtAreaDescription,
                  newProductMgmtAreaLabel,
                  newProductMgmtBody,
                  newProductMgmtChangeNote,
                  newProductMgmtPriority,
                  newProductMgmtStatus,
                  newProductMgmtTitle,
                  openAskSubmissionReview,
                  productMgmtAreas,
                  productMgmtItemDraft,
                  productMgmtItems,
                  resolvingProductMgmtItemId,
                  retiringProductMgmtAreaId,
                  savingProductMgmtArea,
                  savingProductMgmtEditItemId,
                  savingProductMgmtItem,
                  selectedProductMgmtArea,
                  selectedProductMgmtItems,
                  selectedProductMgmtSection,
                  selectedProductMgmtSectionConfig,
                  setNewProductMgmtAreaDescription,
                  setNewProductMgmtAreaLabel,
                  setNewProductMgmtBody,
                  setNewProductMgmtChangeNote,
                  setNewProductMgmtPriority,
                  setNewProductMgmtStatus,
                  setNewProductMgmtTitle,
                  setShowProductMgmtAreaForm,
                  showProductMgmtAreaForm,
                  startEditingProductMgmtItem,
                  updateProductMgmtItemDraft,
                  visibleProductMgmtSections,
                },
    secondaryItems: systemAdminTabs.includes(adminTab)
                    ? systemAdminNavItems
                    : supportAdminTabs.includes(adminTab)
                      ? supportAdminNavItems
                      : undefined,
    stickyTop: stickySecondaryOffset,
    tickets: {
                  adminTicketCategory,
                  adminTicketChangeNote,
                  adminTicketInternalNote,
                  adminTicketNeedsFollowup,
                  adminTicketPriority,
                  adminTicketReplyBody,
                  adminTicketStatus,
                  formatDate,
                  lastViewedAt: adminLastViewedAt("admin_tab", "tickets"),
                  loading: loadingAdminTickets,
                  messages: selectedAdminTicketMessages,
                  onAddInternalNote: handleAddAdminInternalNote,
                  onAddReply: handleAddAdminTicketReply,
                  onOpenAskSubmission: openAskSubmissionReview,
                  onRefresh: loadAdminSupportTickets,
                  onSelectTicket: selectAdminTicket,
                  onSetCategory: setAdminTicketCategory,
                  onSetChangeNote: setAdminTicketChangeNote,
                  onSetInternalNote: setAdminTicketInternalNote,
                  onSetNeedsFollowup: setAdminTicketNeedsFollowup,
                  onSetPriority: setAdminTicketPriority,
                  onSetReplyBody: setAdminTicketReplyBody,
                  onSetStatus: setAdminTicketStatus,
                  onUpdateStatus: handleUpdateAdminTicketStatus,
                  savingReply: savingAdminTicketReply,
                  savingStatus: savingAdminTicketStatus,
                  selectedTicket: selectedAdminTicket,
                  tickets: adminSupportTickets,
                },
    tools: {
                  adminEmailUpdateCurrentEmail,
                  adminEmailUpdateNewEmail,
                  adminEmailUpdateReason,
                  adminEmailUpdateResult,
                  adminSampleEmail,
                  adminSampleForceDeclined,
                  adminSampleStatus,
                  appSessionSettings,
                  loadingAdminSampleStatus,
                  onChangeAdminEmailUpdateCurrentEmail:
                    setAdminEmailUpdateCurrentEmail,
                  onChangeAdminEmailUpdateNewEmail: setAdminEmailUpdateNewEmail,
                  onChangeAdminEmailUpdateReason: setAdminEmailUpdateReason,
                  onChangeAdminSampleEmail: setAdminSampleEmail,
                  onChangeAdminSampleForceDeclined:
                    setAdminSampleForceDeclined,
                  onChangeAppSessionSettings: setAppSessionSettings,
                  onClearAdminEmailUpdateResult: () =>
                    setAdminEmailUpdateResult(""),
                  onClearAdminSampleStatus: () => setAdminSampleStatus(null),
                  onLoadAdminSampleStatus: handleLoadAdminSampleStatus,
                  onSaveAppSessionSettings: handleSaveAppSessionSettings,
                  onSeedAdminSampleData: handleSeedAdminSampleData,
                  onSubmitAdminUpdateUserEmail: handleAdminUpdateUserEmail,
                  sampleDataStatusText,
                  savingAppSessionSettings,
                  seedingAdminSampleData,
                  updatingAdminUserEmail,
                },
    topItems: topAdminNavItems,
    users: {
                  activeKey: adminTab,
                  adminReadonlyPanelRef,
                  adminReadonlySnapshot,
                  adminRevealedSensitiveData,
                  adminUserActivity,
                  adminUserActivityFilter,
                  adminUserActivitySort,
                  adminUserActivityStats,
                  closeAdminReadonlyUserView,
                  expandedAdminUserCareVipRows,
                  filteredAdminUserActivity,
                  formatAdminDate,
                  formatDate,
                  formatDateOnly,
                  loadingAdminReadonlyUserId,
                  loadingAdminUserActivity,
                  navItems: usersAdminNavItems,
                  onRefresh: loadAdminUserActivity,
                  onSelectTab: handleChangeAdminTab,
                  openAdminReadonlyUserView,
                  revealAdminSensitiveData,
                  revealingAdminSensitiveKey,
                  saveAdminContactDetails,
                  savingAdminContactDetails,
                  setAdminUserActivityFilter,
                  setExpandedAdminUserCareVipRows,
                  shortId,
                  toggleAdminUserActivitySort,
                },
  };
}
