"use client";

import { formatAdminDate, shortId } from "./adminFormatters";
import type { AdminWorkspaceProps } from "./AdminWorkspace";

// Admin state still originates in CarePlandPers during the route split.
// This adapter keeps the panel wiring owned by the Admin island while that state moves over gradually.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AdminWorkspaceSourceProps = Record<string, any>;

export function createAdminWorkspaceProps({
  activeAdminTopTab,
  adminAccessEvents,
  adminAskAnalysisRuns,
  adminAskAnalysisSelectionIds,
  adminAskNeedsResponse,
  adminAskQualitySubmissions,
  adminAskWorkspaceMessages,
  adminAskWorkspaceReviews,
  adminAskWorkspaceSubmission,
  adminAskWorkspaceThread,
  adminAttentionFor,
  adminDashboardFollowupCount,
  adminDashboardNewCount,
  adminEmailUpdateCurrentEmail,
  adminEmailUpdateNewEmail,
  adminEmailUpdateReason,
  adminEmailUpdateResult,
  adminIntegrationErrorRowKey,
  adminIntegrationErrorStats,
  adminIntegrationErrors,
  adminLastViewedAt,
  adminOpenHelpReports,
  adminPriorities,
  adminPrioritiesError,
  adminPrioritiesSummary,
  adminReadonlyPanelRef,
  adminReadonlySnapshot,
  adminRevealedSensitiveData,
  adminSampleEmail,
  adminSampleForceDeclined,
  adminSampleStatus,
  adminTab,
  adminTabForTopTab,
  adminUserActivity,
  adminUserActivityFilter,
  adminUserActivitySort,
  adminUserActivityStats,
  showInactiveAdminUsers,
  agentEscalationGuidance,
  agentKnowledgeAutomationSettings,
  agentKnowledgeChangeNote,
  agentKnowledgeCheckRuns,
  agentKnowledgeProposalDrafts,
  agentKnowledgeProposalNotes,
  agentKnowledgeProposalPublishNote,
  agentKnowledgeProposals,
  agentKnowledgeVersions,
  agentKnownLimitations,
  agentProductFacts,
  agentVoiceGuidance,
  aiAdminTab,
  aiInstructionVersion,
  aiInstructionVersions,
  aiOperationCostError,
  aiOperationCostLogFailureCount,
  aiOperationCostRangeDays,
  aiOperationCostSummary,
  aiOperationCostUserSummary,
  aiOperationCostViewMode,
  aiWorkflows,
  allAdminIntegrationErrorsSelected,
  analyzingAdminAskSubmissions,
  appContentBody,
  appContentCategories,
  appContentChangeNote,
  appContentDescription,
  appContentLabel,
  appContentOptions,
  appContentSaveMessage,
  appContentVersions,
  appSessionSettings,
  appointments,
  askModuleLabInput,
  askModuleLabKey,
  askModuleLabResults,
  askRoutingSettingsDraft,
  cancelEditingProductMgmtItem,
  careSubjects,
  carePrepHistory,
  closeAdminReadonlyUserView,
  deleteSelectedAdminIntegrationErrors,
  deletingAdminIntegrationErrors,
  draftSourceVersion,
  earlyAccessIntakeAdminNotes,
  earlyAccessIntakeDraft,
  earlyAccessIntakeFilter,
  earlyAccessIntakeRows,
  earlyAccessIntakeStats,
  editingProductMgmtItemId,
  evaluateAdminNavItems,
  evaluateAdminTabs,
  expandedAdminUserCareVipRows,
  filteredAdminUserActivity,
  filteredAppContentOptions,
  filteredEarlyAccessIntakeRows,
  formatDate,
  formatDateOnly,
  handleAdminAskQuickStatus,
  handleAdminUpdateUserEmail,
  handleChangeAdminPriorityStatus,
  handleChangeAdminTab,
  handleChangeAiOperationCostRange,
  handleChangeAiAdminTab,
  handleChangeAiWorkflow,
  handleChangeAppContentCategory,
  handleChangeAppContentKey,
  handleChangeHistoryAppointment,
  handleChangeProductMgmtSection,
  handleCreateAdminAskProductItem,
  handleDeferAdminPriority,
  handleCreateEarlyAccessIntake,
  handleCreateProductMgmtArea,
  handleCreateProductMgmtItem,
  handleLoadAdminSampleStatus,
  handlePublishAgentKnowledgeProposal,
  handleQueueAgentKnowledgeManualCheck,
  handleResolveProductMgmtItem,
  handleRetireProductMgmtArea,
  handleRevertAppContent,
  handleRevertInstructionVersion,
  handleReviewAgentKnowledgeProposalItem,
  handleRunAdminAskAnalysis,
  handleRunAskModuleLab,
  handleSaveAgentKnowledge,
  handleSaveAgentKnowledgeAutomationSettings,
  handleSaveAiInstructions,
  handleSaveAppContent,
  handleSaveAppSessionSettings,
  handleSeedAdminSampleData,
  handleSendAdminAsk,
  handleSetUserAdmin,
  handleSetUserLifecycle,
  handleUpdateAdminAskAnalysisRun,
  handleUpdateAskRoutingSettings,
  handleUpdateEarlyAccessIntake,
  handleUpdateProductMgmtItem,
  historyAppointmentId,
  instructionChangeNote,
  instructionModel,
  instructionOutputSchema,
  instructionSystemPrompt,
  instructionUserPrompt,
  intakeHistory,
  isNewForAdmin,
  loadAdminAccessEvents,
  loadAdminAskQueues,
  loadAdminAttentionOverview,
  loadAdminIntegrationErrors,
  loadAdminPriorities,
  loadAdminUserActivity,
  loadAgentKnowledgeProposals,
  loadAiInstructions,
  loadAppContent,
  loadCarePrepHistory,
  loadEarlyAccessIntake,
  loadInstructionVersionIntoEditor,
  loadIntakeHistory,
  loadingAdminAccessEvents,
  loadingAdminAskQueues,
  loadingAdminAskWorkspace,
  loadingAdminIntegrationErrors,
  loadingAdminPriorities,
  loadingAdminReadonlyUserId,
  loadingAdminSampleStatus,
  loadingAdminUserActivity,
  loadingAgentKnowledgeProposals,
  loadingAiOperationCosts,
  loadingAppContent,
  loadingAskRoutingSettings,
  loadingCarePrepHistory,
  loadingEarlyAccessIntake,
  loadingInstructions,
  loadingProductMgmt,
  newProductMgmtAreaDescription,
  newProductMgmtAreaLabel,
  newProductMgmtBody,
  newProductMgmtChangeNote,
  newProductMgmtPriority,
  newProductMgmtStatus,
  newProductMgmtTitle,
  openAdminAskSubmissionInConsole,
  openAdminPriorityDestination,
  openAdminReadonlyUserView,
  productMgmtAreas,
  productMgmtItemDraft,
  productMgmtItems,
  publishingAgentKnowledgeProposalId,
  queueingAgentKnowledgeRun,
  resetAppContentEditor,
  resolvingProductMgmtItemId,
  retiringProductMgmtAreaId,
  revealAdminSensitiveData,
  revealingAdminSensitiveKey,
  revertingAppContentForId,
  revertingInstructionForId,
  runningAskModuleLab,
  sampleDataStatusText,
  saveAdminContactDetails,
  savingAdminContactDetails,
  savingAdminAskProductItem,
  savingAdminAskQuickStatus,
  savingAdminAskSend,
  savingAgentKnowledge,
  savingAgentKnowledgeAutomationSettings,
  savingAgentKnowledgeProposalItemId,
  savingAppContent,
  savingAppSessionSettings,
  savingAskRoutingSettings,
  savingEarlyAccessIntake,
  savingInstructions,
  savingProductMgmtArea,
  savingProductMgmtEditItemId,
  savingProductMgmtItem,
  seedingAdminSampleData,
  selectAdminAskSubmission,
  selectAdminAskThread,
  selectedAdminAskThreadId,
  selectedAdminIntegrationErrorKeys,
  selectedAgentKnowledgeProposal,
  selectedAgentKnowledgeProposalItems,
  selectedAgentKnowledgeProposalPublishableCount,
  selectedAiWorkflow,
  selectedAiWorkflowConfig,
  selectedAppContent,
  selectedAppContentCategory,
  selectedAppContentCategoryConfig,
  selectedAppContentKey,
  selectedProductMgmtArea,
  selectedProductMgmtItems,
  selectedProductMgmtSection,
  selectedProductMgmtSectionConfig,
  selectedVisibleAdminIntegrationErrorKeys,
  setAdminEmailUpdateCurrentEmail,
  setAdminEmailUpdateNewEmail,
  setAdminEmailUpdateReason,
  setAdminEmailUpdateResult,
  setAdminRecommendationsReviewDraftSummary,
  setAdminSampleEmail,
  setAdminSampleForceDeclined,
  setAdminSampleStatus,
  setAdminUserActivityFilter,
  setShowInactiveAdminUsers,
  setAgentEscalationGuidance,
  setAiOperationCostViewMode,
  setAgentKnowledgeAutomationSettings,
  setAgentKnowledgeChangeNote,
  setAgentKnowledgeProposalDrafts,
  setAgentKnowledgeProposalNotes,
  setAgentKnowledgeProposalPublishNote,
  setAgentKnownLimitations,
  setAgentProductFacts,
  setAgentVoiceGuidance,
  setAppContentBody,
  setAppContentChangeNote,
  setAppContentDescription,
  setAppContentLabel,
  setAppSessionSettings,
  setAskModuleLabInput,
  setAskModuleLabKey,
  setAskRoutingSettingsDraft,
  setEarlyAccessIntakeAdminNotes,
  setEarlyAccessIntakeFilter,
  setExpandedAdminUserCareVipRows,
  setInstructionChangeNote,
  setInstructionModel,
  setInstructionOutputSchema,
  setInstructionSystemPrompt,
  setInstructionUserPrompt,
  setNewProductMgmtAreaDescription,
  setNewProductMgmtAreaLabel,
  setNewProductMgmtBody,
  setNewProductMgmtChangeNote,
  setNewProductMgmtPriority,
  setNewProductMgmtStatus,
  setNewProductMgmtTitle,
  setSelectedAgentKnowledgeProposalId,
  setSelectedAiWorkflow,
  setShowProductMgmtAreaForm,
  showProductMgmtAreaForm,
  startEditingProductMgmtItem,
  stickySecondaryOffset,
  supportAdminNavItems,
  supportAdminTabs,
  systemAdminNavItems,
  systemAdminTabs,
  toggleAdminAskAnalysisSelection,
  toggleAdminIntegrationErrorSelection,
  toggleAdminUserActivitySort,
  toggleAllAdminIntegrationErrors,
  topAdminNavItems,
  updateEarlyAccessIntakeDraft,
  updateProductMgmtItemDraft,
  updatingAdminUserEmail,
  updatingEarlyAccessIntakeId,
  usersAdminNavItems,
  visibleProductMgmtSections,
}: AdminWorkspaceSourceProps): AdminWorkspaceProps {
  const recommendationsReviewProps = {
    careSubjects: (careSubjects ?? []).map(
      (subject: {
        care_circle_id: string;
        display_name: string;
        id: string;
      }) => ({
        careCircleId: subject.care_circle_id,
        displayName: subject.display_name,
        id: subject.id,
      })
    ),
    formatDate: (value: string | null | undefined) => formatAdminDate(value ?? null),
    onDraftSummaryChange: setAdminRecommendationsReviewDraftSummary,
  };

  return {
    activeSecondaryKey: adminTab,
    activeTopKey: activeAdminTopTab,
    ai: {
                  adminAttentionFor,
                  agentEscalationGuidance,
                  agentKnowledgeAutomationSettings,
                  agentKnowledgeChangeNote,
                  agentKnowledgeCheckRuns,
                  agentKnowledgeProposalDrafts,
                  agentKnowledgeProposalNotes,
                  agentKnowledgeProposalPublishNote,
                  agentKnowledgeProposals,
                  agentKnowledgeVersions,
                  agentKnownLimitations,
                  agentProductFacts,
                  agentVoiceGuidance,
                  aiAdminTab,
                  aiInstructionVersion,
                  aiInstructionVersions,
                  aiWorkflows,
                  appointments,
                  carePrepHistory,
                  draftSourceVersion,
                  formatDate,
                  handleChangeAiAdminTab,
                  handleChangeAiWorkflow: (workflowKey: string) =>
                    handleChangeAiWorkflow(workflowKey),
                  handlePublishAgentKnowledgeProposal,
                  handleQueueAgentKnowledgeManualCheck,
                  handleReviewAgentKnowledgeProposalItem,
                  handleRevertInstructionVersion,
                  handleSaveAgentKnowledge,
                  handleSaveAgentKnowledgeAutomationSettings,
                  handleSaveAiInstructions,
                  historyAppointmentId,
                  instructionChangeNote,
                  instructionModel,
                  instructionOutputSchema,
                  instructionSystemPrompt,
                  instructionUserPrompt,
                  intakeHistory,
                  loadAgentKnowledgeProposals,
                  loadAiInstructions,
                  loadCarePrepHistory,
                  loadInstructionVersionIntoEditor,
                  loadIntakeHistory,
                  loadingAgentKnowledgeProposals,
                  loadingCarePrepHistory,
                  loadingInstructions,
                  onChangeAgentKnowledgeAutomationSettings: (
                    patch: Record<string, unknown>
                  ) =>
                    setAgentKnowledgeAutomationSettings(
                      (current: Record<string, unknown>) => ({
                        ...current,
                        ...patch,
                      })
                    ),
                  onChangeAgentKnowledgeProposalDraft: (
                    itemId: string,
                    value: string
                  ) =>
                    setAgentKnowledgeProposalDrafts(
                      (current: Record<string, string>) => ({
                        ...current,
                        [itemId]: value,
                      })
                    ),
                  onChangeAgentKnowledgeProposalNote: (
                    itemId: string,
                    value: string
                  ) =>
                    setAgentKnowledgeProposalNotes(
                      (current: Record<string, string>) => ({
                        ...current,
                        [itemId]: value,
                      })
                    ),
                  onChangeHistoryAppointment: handleChangeHistoryAppointment,
                  onLoadAgentKnowledgeContent: () =>
                    loadAppContent("support_agent_product_facts"),
                  publishingAgentKnowledgeProposalId,
                  queueingAgentKnowledgeRun,
                  revertingInstructionForId,
                  savingAgentKnowledge,
                  savingAgentKnowledgeAutomationSettings,
                  savingAgentKnowledgeProposalItemId,
                  savingInstructions,
                  selectedAgentKnowledgeProposal,
                  selectedAgentKnowledgeProposalItems,
                  selectedAgentKnowledgeProposalPublishableCount,
                  selectedAiWorkflow,
                  selectedAiWorkflowConfig,
                  setAgentEscalationGuidance,
                  setAgentKnowledgeChangeNote,
                  setAgentKnowledgeProposalPublishNote,
                  setAgentKnownLimitations,
                  setAgentProductFacts,
                  setAgentVoiceGuidance,
                  setInstructionChangeNote,
                  setInstructionModel,
                  setInstructionOutputSchema,
                  setInstructionSystemPrompt,
                  setInstructionUserPrompt,
                  setSelectedAgentKnowledgeProposalId,
                },
    askConsole: {
                  analysisRuns: adminAskAnalysisRuns,
                  analyzingSubmissions: analyzingAdminAskSubmissions,
                  formatDate,
                  lastViewedAt: adminLastViewedAt("admin_tab", "askConsole"),
                  loadingQueues: loadingAdminAskQueues,
                  loadingSettings: loadingAskRoutingSettings,
                  loadingThread: loadingAdminAskWorkspace,
                  moduleLabInput: askModuleLabInput,
                  moduleLabKey: askModuleLabKey,
                  moduleLabResults: askModuleLabResults,
                  moduleLabRunning: runningAskModuleLab,
                  needsResponseThreads: adminAskNeedsResponse,
                  onCreateProductItem: handleCreateAdminAskProductItem,
                  onQuickSetStatus: handleAdminAskQuickStatus,
                  onRefresh: loadAdminAskQueues,
                  onRunAnalysis: handleRunAdminAskAnalysis,
                  onRunModuleLab: handleRunAskModuleLab,
                  onSelectSubmission: selectAdminAskSubmission,
                  onSelectThread: selectAdminAskThread,
                  onSend: handleSendAdminAsk,
                  onSetModuleLabInput: setAskModuleLabInput,
                  onSetModuleLabKey: setAskModuleLabKey,
                  onSetSettingsDraft: setAskRoutingSettingsDraft,
                  onUpdateAnalysisRun: handleUpdateAdminAskAnalysisRun,
                  onUpdateSettings: handleUpdateAskRoutingSettings,
                  productAreas: (productMgmtAreas ?? []).map(
                    (area: { area_key: string; label: string }) => ({
                      area_key: area.area_key,
                      label: area.label,
                    })
                  ),
                  qualitySubmissions: adminAskQualitySubmissions,
                  reviewHistory: adminAskWorkspaceReviews,
                  saving: savingAdminAskSend,
                  savingProductItem: savingAdminAskProductItem,
                  savingQuickStatus: savingAdminAskQuickStatus,
                  savingSettings: savingAskRoutingSettings,
                  selectedSubmission: adminAskWorkspaceSubmission,
                  selectedSubmissionIdsForAnalysis: adminAskAnalysisSelectionIds,
                  selectedThread: adminAskWorkspaceThread,
                  selectedThreadId: selectedAdminAskThreadId,
                  settingsDraft: askRoutingSettingsDraft,
                  threadMessages: adminAskWorkspaceMessages,
                  toggleSubmissionForAnalysis: toggleAdminAskAnalysisSelection,
                },
    audit: {
                  activeKey: adminTab,
                  formatAdminDate,
                  loading: loadingAdminAccessEvents,
                  navItems: usersAdminNavItems,
                  onRefresh: loadAdminAccessEvents,
                  onSelectTab: handleChangeAdminTab,
                  rows: adminAccessEvents,
                  shortId,
                  userRows: adminUserActivity,
    },
    checkpoint: {
      formatDate,
    },
    content: {
                  appContentBody,
                  appContentCategories,
                  appContentChangeNote,
                  appContentDescription,
                  appContentLabel,
                  appContentOptions,
                  appContentSaveMessage,
                  appContentVersions,
                  filteredAppContentOptions,
                  formatDate,
                  handleChangeAppContentCategory,
                  handleChangeAppContentKey,
                  handleRevertAppContent,
                  handleSaveAppContent,
                  loadAppContent,
                  loadingAppContent,
                  resetAppContentEditor,
                  revertingAppContentForId,
                  savingAppContent,
                  selectedAppContent,
                  selectedAppContentCategory,
                  selectedAppContentCategoryConfig,
                  selectedAppContentKey,
                  setAppContentBody,
                  setAppContentChangeNote,
                  setAppContentDescription,
                  setAppContentLabel,
                },
    dashboard: {
                  aiOperationCostError,
                  aiOperationCostLogFailureCount,
                  aiOperationCostRangeDays,
                  aiOperationCostRows: aiOperationCostSummary,
                  aiOperationCostUserRows: aiOperationCostUserSummary,
                  aiOperationCostViewMode,
                  earlyAccessFollowups: (earlyAccessIntakeRows ?? []).filter(
                    (row: { status: string }) =>
                      ["new", "reviewing", "contacted", "interested"].includes(
                        row.status
                      )
                  ),
                  followupCount: adminDashboardFollowupCount,
                  integrationErrorRows: adminIntegrationErrors,
                  loadingAdminPriorities,
                  loadingAiOperationCosts,
                  needsResponseThreads: adminAskNeedsResponse,
                  newCount: adminDashboardNewCount,
                  onChangeAiOperationCostRange: handleChangeAiOperationCostRange,
                  onChangeAiOperationCostViewMode: setAiOperationCostViewMode,
                  onChangePriorityStatus: handleChangeAdminPriorityStatus,
                  onDeferPriority: handleDeferAdminPriority,
                  onOpenEarlyAccessFollowup: () =>
                    void handleChangeAdminTab("intake"),
                  onOpenErrors: () => void handleChangeAdminTab("errors"),
                  onOpenHelpReport: () => void handleChangeAdminTab("helpReports"),
                  onOpenPriorityDestination: openAdminPriorityDestination,
                  onOpenPrioritizationPrompt: () => {
                    setSelectedAiWorkflow("admin_hq_prioritization");
                    void handleChangeAdminTab("ai");
                  },
                  onOpenSupportThread: (threadId: string) => {
                    selectAdminAskThread(threadId);
                    void handleChangeAdminTab("askConsole");
                  },
                  onRefreshSignals: () => {
                    void loadAdminAttentionOverview();
                    void loadAdminPriorities();
                  },
                  openHelpReports: adminOpenHelpReports,
                  priorities: adminPriorities,
                  prioritiesError: adminPrioritiesError,
                  prioritiesSummary: adminPrioritiesSummary,
                },
    errors: {
                  allSelected: allAdminIntegrationErrorsSelected,
                  deleting: deletingAdminIntegrationErrors,
                  formatAdminDate,
                  lastViewedAt: adminLastViewedAt("admin_tab", "errors"),
                  loading: loadingAdminIntegrationErrors,
                  onDeleteSelected: deleteSelectedAdminIntegrationErrors,
                  onRefresh: loadAdminIntegrationErrors,
                  onToggleAll: toggleAllAdminIntegrationErrors,
                  onToggleRow: toggleAdminIntegrationErrorSelection,
                  rowKey: adminIntegrationErrorRowKey,
                  rows: adminIntegrationErrors,
                  selectedKeys: selectedAdminIntegrationErrorKeys,
                  selectedVisibleCount:
                    selectedVisibleAdminIntegrationErrorKeys.length,
                  stats: adminIntegrationErrorStats,
                },
    intake: {
                  activeKey: adminTab,
                  adminNotes: earlyAccessIntakeAdminNotes,
                  draft: earlyAccessIntakeDraft,
                  filter: earlyAccessIntakeFilter,
                  filteredRows: filteredEarlyAccessIntakeRows,
                  formatAdminDate,
                  loading: loadingEarlyAccessIntake,
                  navItems: usersAdminNavItems,
                  onCreate: handleCreateEarlyAccessIntake,
                  onRefresh: loadEarlyAccessIntake,
                  onSelectTab: handleChangeAdminTab,
                  onUpdateDraft: updateEarlyAccessIntakeDraft,
                  onUpdateRow: handleUpdateEarlyAccessIntake,
                  rows: earlyAccessIntakeRows,
                  saving: savingEarlyAccessIntake,
                  setAdminNotes: setEarlyAccessIntakeAdminNotes,
                  setFilter: setEarlyAccessIntakeFilter,
                  stats: earlyAccessIntakeStats,
                  updatingId: updatingEarlyAccessIntakeId,
                },
    onSelectSecondary: handleChangeAdminTab,
    onSelectTop: (topTab: string) =>
                  handleChangeAdminTab(adminTabForTopTab(topTab)),
    product: {
                  cancelEditingProductMgmtItem,
                  editingProductMgmtItemId,
                  formatDate,
                  handleChangeProductMgmtSection,
                  handleCreateProductMgmtArea,
                  handleCreateProductMgmtItem,
                  handleResolveProductMgmtItem,
                  handleRetireProductMgmtArea,
                  handleUpdateProductMgmtItem,
                  loadingProductMgmt,
                  newProductMgmtAreaDescription,
                  newProductMgmtAreaLabel,
                  newProductMgmtBody,
                  newProductMgmtChangeNote,
                  newProductMgmtPriority,
                  newProductMgmtStatus,
                  newProductMgmtTitle,
                  openAskSubmissionReview: openAdminAskSubmissionInConsole,
                  productMgmtAreas,
                  productMgmtItemDraft,
                  productMgmtItems,
                  resolvingProductMgmtItemId,
                  retiringProductMgmtAreaId,
                  savingProductMgmtArea,
                  savingProductMgmtEditItemId,
                  savingProductMgmtItem,
                  selectedProductMgmtArea,
                  selectedProductMgmtItems,
                  selectedProductMgmtSection,
                  selectedProductMgmtSectionConfig,
                  setNewProductMgmtAreaDescription,
                  setNewProductMgmtAreaLabel,
                  setNewProductMgmtBody,
                  setNewProductMgmtChangeNote,
                  setNewProductMgmtPriority,
                  setNewProductMgmtStatus,
                  setNewProductMgmtTitle,
                  setShowProductMgmtAreaForm,
                  showProductMgmtAreaForm,
                  startEditingProductMgmtItem,
                  updateProductMgmtItemDraft,
                  visibleProductMgmtSections,
                },
    secondaryItems: systemAdminTabs.includes(adminTab)
                    ? systemAdminNavItems
                    : supportAdminTabs.includes(adminTab)
                      ? supportAdminNavItems
                      : evaluateAdminTabs.includes(adminTab)
                        ? evaluateAdminNavItems
                        : undefined,
    recommendations: recommendationsReviewProps,
    stickyTop: stickySecondaryOffset,
    tools: {
                  adminEmailUpdateCurrentEmail,
                  adminEmailUpdateNewEmail,
                  adminEmailUpdateReason,
                  adminEmailUpdateResult,
                  adminSampleEmail,
                  adminSampleForceDeclined,
                  adminSampleStatus,
                  appSessionSettings,
                  recommendationsReview: recommendationsReviewProps,
                  loadingAdminSampleStatus,
                  onChangeAdminEmailUpdateCurrentEmail:
                    setAdminEmailUpdateCurrentEmail,
                  onChangeAdminEmailUpdateNewEmail: setAdminEmailUpdateNewEmail,
                  onChangeAdminEmailUpdateReason: setAdminEmailUpdateReason,
                  onChangeAdminSampleEmail: setAdminSampleEmail,
                  onChangeAdminSampleForceDeclined:
                    setAdminSampleForceDeclined,
                  onChangeAppSessionSettings: setAppSessionSettings,
                  onClearAdminEmailUpdateResult: () =>
                    setAdminEmailUpdateResult(""),
                  onClearAdminSampleStatus: () => setAdminSampleStatus(null),
                  onLoadAdminSampleStatus: handleLoadAdminSampleStatus,
                  onSaveAppSessionSettings: handleSaveAppSessionSettings,
                  onSeedAdminSampleData: handleSeedAdminSampleData,
                  onSubmitAdminUpdateUserEmail: handleAdminUpdateUserEmail,
                  sampleDataStatusText,
                  savingAppSessionSettings,
                  seedingAdminSampleData,
                  updatingAdminUserEmail,
                },
    topItems: topAdminNavItems,
    users: {
                  activeKey: adminTab,
                  adminReadonlyPanelRef,
                  adminReadonlySnapshot,
                  adminRevealedSensitiveData,
                  adminUserActivity,
                  adminUserActivityFilter,
                  adminUserActivitySort,
                  adminUserActivityStats,
                  closeAdminReadonlyUserView,
                  expandedAdminUserCareVipRows,
                  filteredAdminUserActivity,
                  formatAdminDate,
                  formatDate,
                  formatDateOnly,
                  loadingAdminReadonlyUserId,
                  loadingAdminUserActivity,
                  navItems: usersAdminNavItems,
                  onRefresh: loadAdminUserActivity,
                  onShowInactiveAccountsChange: setShowInactiveAdminUsers,
                  onSelectTab: handleChangeAdminTab,
                  onSetUserAdmin: handleSetUserAdmin,
                  onSetUserLifecycle: handleSetUserLifecycle,
                  openAdminReadonlyUserView,
                  revealAdminSensitiveData,
                  revealingAdminSensitiveKey,
                  saveAdminContactDetails,
                  savingAdminContactDetails,
                  setAdminUserActivityFilter,
                  setExpandedAdminUserCareVipRows,
                  showInactiveAccounts: showInactiveAdminUsers,
                  shortId,
                  toggleAdminUserActivitySort,
                },
  };
}
